# Generated by Django 5.2.7 on 2025-11-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_alter_rating_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='active_update_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
