# Generated by Django 5.2.7 on 2025-11-28 20:54

import exports.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(null=True, upload_to=exports.models.export_file_handler)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
